CREATE TABLE IF NOT EXISTS roles(
     id INT AUTO_INCREMENT PRIMARY KEY,
     permissions TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    role_id FOREIGN KEY REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS subscribes(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    authorization TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS business(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    subscribe_id FOREIGN KEY REFERENCES subscribes(id)
);

CREATE TABLE IF NOT EXISTS clients(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    business_id FOREIGN KEY REFERENCES business(id)
);

CREATE TABLE IF NOT EXISTS places(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    capacity INT NOT NULL DEFAULT 1,
    business_id FOREIGN KEY REFERENCES business(id),
);

CREATE TABLE IF NOT EXISTS places_datetime(
    id INT AUTO_INCREMENT PRIMARY KEY,
    datetime_start DATETIME NOT NULL,
    datetime_end DATETIME NOT NULL,
    place_id FOREIGN KEY REFERENCES places(id)
);

CREATE TABLE IF NOT EXISTS reservations(
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_id FOREIGN KEY REFERENCES clients(id),
    place_id FOREIGN KEY REFERENCES places(id)
    place_datetime_id FOREIGN KEY REFERENCES places_datetime(id)
);
