CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(13) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255) NOT NULL,
  role ENUM('admin', 'user') DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS houses (
  id VARCHAR(13) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  rooms INT NOT NULL,
  capacity INT NOT NULL,
  images_url TEXT NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS reservations (
  id VARCHAR(13) PRIMARY KEY,
  house_id VARCHAR(13) NOT NULL,
  user_id VARCHAR(13) NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  message TEXT NOT NULL,
  total_price DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (house_id) REFERENCES houses(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
)